import AppKit
import Foundation

@MainActor
final class ClipboardMonitor {
    private let pasteboard = NSPasteboard.general
    private var timer: Timer?
    private var onCapture: ((ClipboardItem) -> Void)?
    private var lastChangeCount: Int
    private var ignoredSignatures: [String: Int] = [:]
    private var isPaused = false

    init() {
        lastChangeCount = pasteboard.changeCount
    }

    func start(onCapture: @escaping (ClipboardItem) -> Void) {
        stop()
        self.onCapture = onCapture
        lastChangeCount = pasteboard.changeCount

        timer = Timer.scheduledTimer(withTimeInterval: 0.35, repeats: true) { [weak self] _ in
            Task { @MainActor [weak self] in
                self?.poll()
            }
        }
    }

    func stop() {
        timer?.invalidate()
        timer = nil
    }

    func setPaused(_ paused: Bool) {
        isPaused = paused
        if paused {
            lastChangeCount = pasteboard.changeCount
        }
    }

    func ignoreNextCapture(for item: ClipboardItem) {
        ignoredSignatures[item.signature, default: 0] += 1
    }

    /// Pasteboard markers from the nspasteboard.org convention. Password managers mark secrets as
    /// concealed, and apps mark short-lived or generated content as transient or auto-generated.
    /// Clipboard never stores these, matching Maccy and Paste.
    static let ignoredPasteboardTypes: Set<String> = [
        "org.nspasteboard.ConcealedType",
        "org.nspasteboard.TransientType",
        "org.nspasteboard.AutoGeneratedType",
        "com.agilebits.onepassword",
        "de.petermaurer.TransientPasteboardType",
    ]

    static func shouldIgnore(types: [NSPasteboard.PasteboardType]) -> Bool {
        types.contains { ignoredPasteboardTypes.contains($0.rawValue) }
    }

    private func poll() {
        let currentChangeCount = pasteboard.changeCount
        guard currentChangeCount != lastChangeCount else { return }
        lastChangeCount = currentChangeCount

        guard !isPaused else { return }
        guard !Self.shouldIgnore(types: pasteboard.types ?? []) else { return }

        let sourceApp = NSWorkspace.shared.frontmostApplication
        guard let capturedItem = ClipboardItem.fromPasteboard(pasteboard, sourceApp: sourceApp) else {
            return
        }

        if let ignoredCount = ignoredSignatures[capturedItem.signature], ignoredCount > 0 {
            ignoredSignatures[capturedItem.signature] = ignoredCount == 1 ? nil : ignoredCount - 1
            return
        }

        onCapture?(capturedItem)
    }
}
