import AppKit
import XCTest
@testable import Clipboard

@MainActor
final class ClipboardMacTests: XCTestCase {
    func testConcealedAndTransientPasteboardTypesAreIgnored() {
        XCTAssertTrue(ClipboardMonitor.shouldIgnore(types: [.string, NSPasteboard.PasteboardType("org.nspasteboard.ConcealedType")]))
        XCTAssertTrue(ClipboardMonitor.shouldIgnore(types: [NSPasteboard.PasteboardType("org.nspasteboard.TransientType")]))
        XCTAssertTrue(ClipboardMonitor.shouldIgnore(types: [NSPasteboard.PasteboardType("org.nspasteboard.AutoGeneratedType")]))
        XCTAssertFalse(ClipboardMonitor.shouldIgnore(types: [.string, .URL, .png]))
    }

    func testHistoryStoreRoundTripsItems() throws {
        let base = FileManager.default.temporaryDirectory.appendingPathComponent(UUID().uuidString, isDirectory: true)
        defer { try? FileManager.default.removeItem(at: base) }
        let store = ClipboardHistoryStore(baseDirectory: base, namespace: "tests")
        let text = try XCTUnwrap(ClipboardItem.fromString("hello subset", sourceAppName: "Tests", sourceBundleIdentifier: nil))
        let link = try XCTUnwrap(ClipboardItem.fromString("https://subset.dev", sourceAppName: "Tests", sourceBundleIdentifier: nil))

        store.save([text, link])
        let loaded = store.load()

        XCTAssertEqual(loaded.map(\.id), [text.id, link.id])
        XCTAssertEqual(loaded.first?.kind, .text)
        XCTAssertEqual(loaded.last?.kind, .url)
    }

    func testDeleteRemovesOnlyTheChosenItemAndPersists() throws {
        let base = FileManager.default.temporaryDirectory.appendingPathComponent(UUID().uuidString, isDirectory: true)
        defer { try? FileManager.default.removeItem(at: base) }
        let store = ClipboardHistoryStore(baseDirectory: base, namespace: "tests")
        let keep = try XCTUnwrap(ClipboardItem.fromString("keep", sourceAppName: "Tests", sourceBundleIdentifier: nil))
        let drop = try XCTUnwrap(ClipboardItem.fromString("drop", sourceAppName: "Tests", sourceBundleIdentifier: nil))
        store.save([keep, drop])

        let manager = ClipboardManager(store: store, startsMonitoring: false)
        manager.delete(drop)

        XCTAssertEqual(manager.items.map(\.id), [keep.id])
        XCTAssertEqual(store.load().map(\.id), [keep.id])
    }
}
