import AppKit
import XCTest
@testable import Clipboard

@MainActor
final class ClipboardMacTests: XCTestCase {
    func testConcealedAndTransientPasteboardTypesAreIgnored() {
        XCTAssertTrue(ClipboardMonitor.shouldIgnore(types: [.string, NSPasteboard.PasteboardType("org.nspasteboard.ConcealedType")]))
        XCTAssertTrue(ClipboardMonitor.shouldIgnore(types: [NSPasteboard.PasteboardType("org.nspasteboard.TransientType")]))
        XCTAssertTrue(ClipboardMonitor.shouldIgnore(types: [NSPasteboard.PasteboardType("org.nspasteboard.AutoGeneratedType")]))
        XCTAssertFalse(ClipboardMonitor.shouldIgnore(types: [.string, .URL, .png]))
    }

    func testHistoryStoreRoundTripsItems() throws {
        let base = FileManager.default.temporaryDirectory.appendingPathComponent(UUID().uuidString, isDirectory: true)
        defer { try? FileManager.default.removeItem(at: base) }
        let store = ClipboardHistoryStore(baseDirectory: base, namespace: "tests")
        let text = try XCTUnwrap(ClipboardItem.fromString("hello subset", sourceAppName: "Tests", sourceBundleIdentifier: nil))
        let link = try XCTUnwrap(ClipboardItem.fromString("https://subset.dev", sourceAppName: "Tests", sourceBundleIdentifier: nil))

        store.save([text, link])
        let loaded = store.load()

        XCTAssertEqual(loaded.map(\.id), [text.id, link.id])
        XCTAssertEqual(loaded.first?.kind, .text)
        XCTAssertEqual(loaded.last?.kind, .url)
        XCTAssertEqual(loaded.map(\.textContent), ["hello subset", "https://subset.dev"])
    }

    func testTextKeepsSurroundingWhitespace() throws {
        let item = try XCTUnwrap(ClipboardItem.fromString("\tlet value = 1\n"))
        XCTAssertEqual(item.kind, .text)
        XCTAssertEqual(item.textContent, "\tlet value = 1\n")
        XCTAssertNotEqual(item.signature, ClipboardItem.fromString("let value = 1")?.signature)
        XCTAssertNil(ClipboardItem.fromString(" \n\t "))
    }

    func testSignatureIncludesKind() throws {
        let text = try XCTUnwrap(ClipboardItem.fromString("/tmp/report.pdf"))
        let file = try XCTUnwrap(ClipboardItem.fileItem(filePaths: ["/tmp/report.pdf"]))
        XCTAssertNotEqual(text.signature, file.signature)
    }

    func testImageWrittenBackKeepsItsSignature() throws {
        let pasteboard = NSPasteboard(name: NSPasteboard.Name("ClipboardTests.\(UUID().uuidString)"))
        defer { pasteboard.releaseGlobally() }
        let image = NSImage(size: NSSize(width: 4, height: 4))
        image.lockFocus()
        NSColor.systemPink.setFill()
        NSRect(x: 0, y: 0, width: 4, height: 4).fill()
        image.unlockFocus()
        let png = try XCTUnwrap(NSBitmapImageRep(data: try XCTUnwrap(image.tiffRepresentation))?.representation(using: .png, properties: [:]))
        let item = ClipboardItem.imageItem(pngData: png)

        XCTAssertTrue(item.write(to: pasteboard))
        let recaptured = try XCTUnwrap(ClipboardItem.fromPasteboard(pasteboard, sourceApp: nil))

        XCTAssertEqual(recaptured.signature, item.signature)
    }

    func testUnreadableHistoryIsKeptAside() throws {
        let base = FileManager.default.temporaryDirectory.appendingPathComponent(UUID().uuidString, isDirectory: true)
        defer { try? FileManager.default.removeItem(at: base) }
        let folder = base.appendingPathComponent("tests", isDirectory: true)
        try FileManager.default.createDirectory(at: folder, withIntermediateDirectories: true)
        try Data("not json".utf8).write(to: folder.appendingPathComponent("history.json"))
        let store = ClipboardHistoryStore(baseDirectory: base, namespace: "tests")

        XCTAssertTrue(store.load().isEmpty)
        XCTAssertNotNil(store.lastLoadIssue)
        let names = try FileManager.default.contentsOfDirectory(atPath: folder.path)
        XCTAssertTrue(names.contains { $0.hasPrefix("history-unreadable-") }, "\(names)")
    }

    func testUpdateAppliesTransformToStoredItems() throws {
        let base = FileManager.default.temporaryDirectory.appendingPathComponent(UUID().uuidString, isDirectory: true)
        defer { try? FileManager.default.removeItem(at: base) }
        let store = ClipboardHistoryStore(baseDirectory: base, namespace: "tests")
        let first = try XCTUnwrap(ClipboardItem.fromString("first"))
        let second = try XCTUnwrap(ClipboardItem.fromString("second"))
        store.save([first])

        let saved = store.update { [second] + $0 }

        XCTAssertEqual(saved?.map(\.id), [second.id, first.id])
        XCTAssertEqual(store.load().map(\.id), [second.id, first.id])
    }

    func testDeleteRemovesOnlyTheChosenItemAndPersists() throws {
        let base = FileManager.default.temporaryDirectory.appendingPathComponent(UUID().uuidString, isDirectory: true)
        defer { try? FileManager.default.removeItem(at: base) }
        let store = ClipboardHistoryStore(baseDirectory: base, namespace: "tests")
        let keep = try XCTUnwrap(ClipboardItem.fromString("keep", sourceAppName: "Tests", sourceBundleIdentifier: nil))
        let drop = try XCTUnwrap(ClipboardItem.fromString("drop", sourceAppName: "Tests", sourceBundleIdentifier: nil))
        store.save([keep, drop])

        let manager = ClipboardManager(store: store, startsMonitoring: false)
        manager.delete(drop)

        XCTAssertEqual(manager.items.map(\.id), [keep.id])
        XCTAssertEqual(store.load().map(\.id), [keep.id])
    }
}
